import 'package:flutter/material.dart';

enum ShopCategory {
  all('All', Icons.grid_view_rounded),
  dice('Dice', Icons.casino_rounded),
  token('Token', Icons.token_rounded),
  theme('Theme', Icons.wallpaper_rounded),
  tile('Tile', Icons.dashboard_rounded),
  bubble('Bubble', Icons.chat_bubble_rounded),
  stickers('Stickers', Icons.sticky_note_2_rounded),
  royal('Royal Exclusives', Icons.military_tech_rounded);

  final String label;
  final IconData icon;
  const ShopCategory(this.label, this.icon);
}

enum CurrencyType {
  coins('Coins', 'assets/graphics/icon_coins.png'),
  diamonds('Diamonds', 'assets/graphics/icon_diamond.png'),
  royalVip('Royal VIP', 'assets/graphics/shop/badges_selection_indicators/Crown.png'),
  free('Free', '');

  final String label;
  final String iconAsset;
  const CurrencyType(this.label, this.iconAsset);
}

enum ThemeType {
  basic,
  royal,
}

enum StickerType {
  pack,
  single,
}

class ShopItem {
  final String id;
  final String name;
  final ShopCategory category;
  final String imageAsset;
  final int price;
  final CurrencyType currencyType;
  final bool isOwned;
  final bool isEquipped;
  final bool isRoyalOnly;
  final String description;
  final ThemeType? themeType;
  final StickerType? stickerType;
  final List<String>? previewAssets;
  final int? royalVipLevel;
  final Color? glowColor;

  const ShopItem({
    required this.id,
    required this.name,
    required this.category,
    required this.imageAsset,
    required this.price,
    this.currencyType = CurrencyType.coins,
    this.isOwned = false,
    this.isEquipped = false,
    this.isRoyalOnly = false,
    this.description = '',
    this.themeType,
    this.stickerType,
    this.previewAssets,
    this.royalVipLevel,
    this.glowColor,
  });

  ShopItem copyWith({
    String? id,
    String? name,
    ShopCategory? category,
    String? imageAsset,
    int? price,
    CurrencyType? currencyType,
    bool? isOwned,
    bool? isEquipped,
    bool? isRoyalOnly,
    String? description,
    ThemeType? themeType,
    StickerType? stickerType,
    List<String>? previewAssets,
    int? royalVipLevel,
    Color? glowColor,
  }) {
    return ShopItem(
      id: id ?? this.id,
      name: name ?? this.name,
      category: category ?? this.category,
      imageAsset: imageAsset ?? this.imageAsset,
      price: price ?? this.price,
      currencyType: currencyType ?? this.currencyType,
      isOwned: isOwned ?? this.isOwned,
      isEquipped: isEquipped ?? this.isEquipped,
      isRoyalOnly: isRoyalOnly ?? this.isRoyalOnly,
      description: description ?? this.description,
      themeType: themeType ?? this.themeType,
      stickerType: stickerType ?? this.stickerType,
      previewAssets: previewAssets ?? this.previewAssets,
      royalVipLevel: royalVipLevel ?? this.royalVipLevel,
      glowColor: glowColor ?? this.glowColor,
    );
  }
}

/// Catalog data source containing all shop items accurately mapped to assets
class ShopCatalog {
  static const List<ShopItem> allItems = [
    // ════════════════════════════════════════════════════════════════════════
    // 1. DICE SKINS
    // ════════════════════════════════════════════════════════════════════════
    ShopItem(
      id: 'dice_classic',
      name: 'Classic',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Classic.png',
      price: 0,
      currencyType: CurrencyType.free,
      isOwned: true,
      isEquipped: true,
      description: 'The standard timeless Ludo dice.',
      glowColor: Color(0xFF5641F8),
    ),
    ShopItem(
      id: 'dice_chick',
      name: 'Chick',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Chick.png',
      price: 5000,
      currencyType: CurrencyType.coins,
      description: 'Cute chirping chick skin for charming luck.',
      glowColor: Color(0xFFFFD369),
    ),
    ShopItem(
      id: 'dice_coffee',
      name: 'Coffee',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Cofee.png',
      price: 8000,
      currencyType: CurrencyType.coins,
      description: 'Warm, energized morning espresso roll.',
      glowColor: Color(0xFFC07A48),
    ),
    ShopItem(
      id: 'dice_crystal',
      name: 'Crystal',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Crystal.png',
      price: 150,
      currencyType: CurrencyType.diamonds,
      description: 'Pure radiant gemstone crystal of fortune.',
      glowColor: Color(0xFF00E5FF),
    ),
    ShopItem(
      id: 'dice_dessert',
      name: 'Dessert',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Dessert.png',
      price: 6500,
      currencyType: CurrencyType.coins,
      description: 'Sweet frosted confectionery celebration piece.',
      glowColor: Color(0xFFFF69B4),
    ),
    ShopItem(
      id: 'dice_earth_power',
      name: 'Earth Power',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Earth_power.png',
      price: 250,
      currencyType: CurrencyType.diamonds,
      description: 'Harness the primordial terra element on each turn.',
      glowColor: Color(0xFF4CAF50),
    ),
    ShopItem(
      id: 'dice_fantasy_book',
      name: 'Fantasy Book',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Fantasy_Book.png',
      price: 12000,
      currencyType: CurrencyType.coins,
      description: 'Ancient spellbook containing magical roll secrets.',
      glowColor: Color(0xFFAB47BC),
    ),
    ShopItem(
      id: 'dice_ice_cream',
      name: 'Ice Cream',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Icecream.png',
      price: 7500,
      currencyType: CurrencyType.coins,
      description: 'Chilled gelato scoop for ultra smooth rolling.',
      glowColor: Color(0xFFFF80AB),
    ),
    ShopItem(
      id: 'dice_leisure_kitty',
      name: 'Leisure Kitty',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Leisure_kitty.png',
      price: 180,
      currencyType: CurrencyType.diamonds,
      description: 'Playful feline buddy bringing purr-fect high numbers.',
      glowColor: Color(0xFFFFB74D),
    ),
    ShopItem(
      id: 'dice_rosy_life',
      name: 'Rosy Life',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Rosy_Life.png',
      price: 10000,
      currencyType: CurrencyType.coins,
      description: 'Blooming crimson petals overflowing with luck.',
      glowColor: Color(0xFFE91E63),
    ),
    ShopItem(
      id: 'dice_warm_campfire',
      name: 'Warm Campfire',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Warm_Campfire.png',
      price: 14000,
      currencyType: CurrencyType.coins,
      description: 'Cozy glowing embers that blaze through opponent tokens.',
      glowColor: Color(0xFFFF5722),
    ),
    ShopItem(
      id: 'dice_warrior_helmet',
      name: 'Warrior Helmet',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Metal.png',
      price: 320,
      currencyType: CurrencyType.diamonds,
      description: 'Armored battle helmet of the invincible champion.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'dice_wooden_case',
      name: 'Wooden Case',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Wooden_Case.png',
      price: 4500,
      currencyType: CurrencyType.coins,
      description: 'Handcrafted polished mahogany treasure chest dice.',
      glowColor: Color(0xFF8D6E63),
    ),
    ShopItem(
      id: 'dice_blessing_basket',
      name: 'Blessing Basket',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Blessing_Basket.png',
      price: 9500,
      currencyType: CurrencyType.coins,
      description: 'Festival basket filled with prosperity and sixes.',
      glowColor: Color(0xFF26A69A),
    ),
    ShopItem(
      id: 'dice_desert_hammer',
      name: 'Desert Hammer',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Desert_Hammer-2.png',
      price: 210,
      currencyType: CurrencyType.diamonds,
      description: 'Forged under dunes to strike down rival pieces.',
      glowColor: Color(0xFFFFA726),
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 2. TOKENS (4-PIECE PAWN SETS)
    // ════════════════════════════════════════════════════════════════════════
    ShopItem(
      id: 'token_classic',
      name: 'Classic Pieces',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Classic.png',
      price: 0,
      currencyType: CurrencyType.free,
      isOwned: true,
      isEquipped: true,
      description: 'The standard timeless Ludo piece set.',
      glowColor: Color(0xFF5641F8),
    ),
    ShopItem(
      id: 'token_chick',
      name: 'Chick Set',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Chick-4.png',
      price: 5000,
      currencyType: CurrencyType.coins,
      description: 'Cute chirping chick pawn pieces.',
      glowColor: Color(0xFFFFD369),
    ),
    ShopItem(
      id: 'token_coffee',
      name: 'Coffee Set',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Cofee-3.png',
      price: 8000,
      currencyType: CurrencyType.coins,
      description: 'Warm energizing coffee cup tokens.',
      glowColor: Color(0xFFC07A48),
    ),
    ShopItem(
      id: 'token_blessing_basket',
      name: 'Blessing Basket',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Blessing_Basket-3.png',
      price: 9500,
      currencyType: CurrencyType.coins,
      description: 'Festival blessing basket pawns.',
      glowColor: Color(0xFF26A69A),
    ),
    ShopItem(
      id: 'token_desert_hammer',
      name: 'Desert Hammer',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Desert_Hammer-2.png',
      price: 210,
      currencyType: CurrencyType.diamonds,
      description: 'Dune forged battle hammer tokens.',
      glowColor: Color(0xFFFFA726),
    ),
    ShopItem(
      id: 'token_earth_power',
      name: 'Earth Power',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Earth_power-7.png',
      price: 250,
      currencyType: CurrencyType.diamonds,
      description: 'Primordial terra crystals of power.',
      glowColor: Color(0xFF4CAF50),
    ),
    ShopItem(
      id: 'token_fantasy_book',
      name: 'Fantasy Book',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Fantasy_Book-3.png',
      price: 12000,
      currencyType: CurrencyType.coins,
      description: 'Ancient spellbook pieces.',
      glowColor: Color(0xFFAB47BC),
    ),
    ShopItem(
      id: 'token_ice_cream',
      name: 'Ice Cream',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Icecream-3.png',
      price: 7500,
      currencyType: CurrencyType.coins,
      description: 'Sweet creamy gelato tokens.',
      glowColor: Color(0xFFFF80AB),
    ),
    ShopItem(
      id: 'token_leisure_kitty',
      name: 'Leisure Kitty',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Leisure_kitty-3.png',
      price: 180,
      currencyType: CurrencyType.diamonds,
      description: 'Playful companion feline pawns.',
      glowColor: Color(0xFFFFB74D),
    ),
    ShopItem(
      id: 'token_rosy_life',
      name: 'Rosy Life',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Rosy_Life-3.png',
      price: 10000,
      currencyType: CurrencyType.coins,
      description: 'Crimson rose petal tokens.',
      glowColor: Color(0xFFE91E63),
    ),
    ShopItem(
      id: 'token_warm_campfire',
      name: 'Warm Campfire',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Warm_Campfire-3.png',
      price: 14000,
      currencyType: CurrencyType.coins,
      description: 'Blazing campfire tokens.',
      glowColor: Color(0xFFFF5722),
    ),
    ShopItem(
      id: 'token_wooden_case',
      name: 'Wooden Case',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Wooden_Case-2.png',
      price: 4500,
      currencyType: CurrencyType.coins,
      description: 'Polished wooden treasure chest tokens.',
      glowColor: Color(0xFF8D6E63),
    ),
    ShopItem(
      id: 'token_crystal',
      name: 'Crystal Pieces',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Crystal.png',
      price: 150,
      currencyType: CurrencyType.diamonds,
      description: 'Pure radiant gemstone crystal piece set.',
      glowColor: Color(0xFF00E5FF),
    ),
    ShopItem(
      id: 'token_dessert',
      name: 'Dessert Pieces',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Dessert.png',
      price: 6500,
      currencyType: CurrencyType.coins,
      description: 'Sweet frosted confectionery celebration tokens.',
      glowColor: Color(0xFFFF69B4),
    ),
    ShopItem(
      id: 'token_warrior_helmet',
      name: 'Warrior Helmet Pieces',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Metal.png',
      price: 320,
      currencyType: CurrencyType.diamonds,
      description: 'Armored metal battle helmet pawn set.',
      glowColor: Color(0xFFFFD700),
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 3. THEMES (BASIC & ROYAL WALLPAPERS)
    // ════════════════════════════════════════════════════════════════════════
    // Basic Themes
    ShopItem(
      id: 'theme_green_silk',
      name: 'Classic Starry',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/basic themes/Starry night.png',
      price: 0,
      currencyType: CurrencyType.free,
      isOwned: true,
      isEquipped: true,
      description: 'Cosmic celestial starry night table board atmosphere.',
    ),
    ShopItem(
      id: 'theme_golden_mountain',
      name: 'Golden Mountain',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/basic themes/Golden Mountain.png',
      price: 20000,
      currencyType: CurrencyType.coins,
      description: 'Magnificent golden peaks glowing under sunlight.',
    ),
    ShopItem(
      id: 'theme_sky_wheel',
      name: 'Sky Wheel',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/basic themes/Sky wheel.png',
      price: 25000,
      currencyType: CurrencyType.coins,
      description: 'Luminous amusement park ferris wheel night vista.',
    ),
    ShopItem(
      id: 'theme_fantastic_lion',
      name: 'Fantastic Lion',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/basic themes/Fantastic lion.png',
      price: 30000,
      currencyType: CurrencyType.coins,
      description: 'Majestic celestial lion overlooking the battlefield.',
    ),
    ShopItem(
      id: 'theme_bonfire',
      name: 'Bonfire Night',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/basic themes/bonfir.png',
      price: 18000,
      currencyType: CurrencyType.coins,
      description: 'Crackling starry night gathering by the warm fire.',
    ),
    ShopItem(
      id: 'theme_waterfall',
      name: 'Waterfall Valley',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/basic themes/waterfall.png',
      price: 22000,
      currencyType: CurrencyType.coins,
      description: 'Cascading pristine alpine waterfalls in lush paradise.',
    ),
    ShopItem(
      id: 'theme_cloudy_sky',
      name: 'Jellyfish Ocean',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/basic themes/jellyfish.png',
      price: 15000,
      currencyType: CurrencyType.coins,
      description: 'Bioluminescent deep ocean jellyfish radiance.',
    ),
    ShopItem(
      id: 'theme_blue_moon',
      name: 'Royal Castle',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/Royal theme/castle.png',
      price: 28000,
      currencyType: CurrencyType.coins,
      description: 'Majestic kingdom citadel glowing at midnight.',
    ),
    ShopItem(
      id: 'theme_eternal_lighthouse',
      name: 'Eternal Mountain',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/Royal theme/Mountain.png',
      price: 32000,
      currencyType: CurrencyType.coins,
      description: 'Guiding mountain peak standing above the clouds.',
    ),
    ShopItem(
      id: 'theme_indigo_wallpaper',
      name: 'Indigo Twilight',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/basic themes/Urban twilight.png',
      price: 16000,
      currencyType: CurrencyType.coins,
      description: 'Deep violet gradient backdrop with glowing city skyline.',
    ),
    ShopItem(
      id: 'theme_urban_twilight',
      name: 'Urban Twilight',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/basic themes/Urban twilight.png',
      price: 24000,
      currencyType: CurrencyType.coins,
      description: 'Modern metropolis skyline lit by glowing neon skyscrapers.',
    ),
    ShopItem(
      id: 'theme_spring_letter',
      name: 'Dream Garden',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/themes/Royal theme/Dream Garden.png',
      price: 19000,
      currencyType: CurrencyType.coins,
      description: 'Enchanted blooming paradise garden breeze.',
    ),

    // Royal Themes
    ShopItem(
      id: 'theme_royal_twilight_knight',
      name: 'Twilight Knight',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/themes/Royal theme/Twilight knight.png',
      price: 500,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 1,
      description: 'Royal armory hall guarded by eternal silver paladins.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'theme_royal_red_car',
      name: 'Red Car Beneath Snow',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/themes/Royal theme/red caar beneath snow.png',
      price: 650,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 1,
      description: 'Luxury grand tourer cruising alpine winter wonderlands.',
      glowColor: Color(0xFFFF5252),
    ),
    ShopItem(
      id: 'theme_royal_couple_dusk',
      name: 'Couple at Dusk',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/themes/Royal theme/couple at dusk.png',
      price: 800,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 2,
      description: 'Romantic sunset promenade with golden hour reflections.',
      glowColor: Color(0xFFFF7043),
    ),
    ShopItem(
      id: 'theme_royal_dream_garden',
      name: 'Dream Garden',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/themes/Royal theme/Dream Garden.png',
      price: 950,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 3,
      description: 'Enchanted palace conservatory filled with bioluminescent flora.',
      glowColor: Color(0xFF7C4DFF),
    ),
    ShopItem(
      id: 'theme_royal_mountain',
      name: 'Mountain Summit',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/themes/Royal theme/Mountain.png',
      price: 1100,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 3,
      description: 'Imperial throne chamber overlooking endless snow peaks.',
      glowColor: Color(0xFF00E5FF),
    ),
    ShopItem(
      id: 'theme_royal_bonfire',
      name: 'Bonfire Night Royal',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/themes/Royal theme/Bonfire night.png',
      price: 1200,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 4,
      description: 'Deep royal starry night gathering around glowing ember flame.',
      glowColor: Color(0xFFFF6D00),
    ),
    ShopItem(
      id: 'theme_royal_castle',
      name: 'Royal Citadel Castle',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/themes/Royal theme/castle.png',
      price: 1500,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'Majestic kingdom citadel illuminated under celestial moonlight.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'theme_royal_supreme_car',
      name: 'Supreme Car',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/themes/Royal theme/Supreme car.png',
      price: 1800,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'Imperial luxury supercar bathed in royal golden reflections.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'theme_royal_knight_sword',
      name: 'Knight Sword',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/themes/Royal theme/knight sword.png',
      price: 2000,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'Legendary knight blade radiating sovereign honor.',
      glowColor: Color(0xFF8C9EFF),
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 3. TILES (BOARD TEXTURE SWATCHES)
    // ════════════════════════════════════════════════════════════════════════
    ShopItem(
      id: 'tile_wood',
      name: 'Classic Wood',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/05_tile_skins_TileTab/Tile1.png',
      price: 0,
      currencyType: CurrencyType.free,
      isOwned: true,
      isEquipped: true,
      description: 'Polished walnut wood parquet texture.',
    ),
    ShopItem(
      id: 'tile_garden',
      name: 'Garden Grass',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/05_tile_skins_TileTab/Tile2.png',
      price: 8000,
      currencyType: CurrencyType.coins,
      description: 'Fresh manicured spring lawn fairway pattern.',
    ),
    ShopItem(
      id: 'tile_egyptian',
      name: 'Egyptian Sand',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/05_tile_skins_TileTab/Tile3.png',
      price: 180,
      currencyType: CurrencyType.diamonds,
      description: 'Hieroglyphic carved golden sandstone tile.',
    ),
    ShopItem(
      id: 'tile_football',
      name: 'Emerald Pitch',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/05_tile_skins_TileTab/Tile4.png',
      price: 12000,
      currencyType: CurrencyType.coins,
      description: 'Stadium turf with precision yard line markings.',
    ),
    ShopItem(
      id: 'tile_basketball',
      name: 'Hardwood Court',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/05_tile_skins_TileTab/image5.png',
      price: 14000,
      currencyType: CurrencyType.coins,
      description: 'Indoor hardwood polished court with paint lines.',
    ),
    ShopItem(
      id: 'tile_purple_silk',
      name: 'Purple Velvet',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/05_tile_skins_TileTab/Tile6.png',
      price: 220,
      currencyType: CurrencyType.diamonds,
      description: 'Imperial velvet tapestry with delicate stitching.',
    ),
    ShopItem(
      id: 'tile_dark_green',
      name: 'Casino Green',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/05_tile_skins_TileTab/Tile7.png',
      price: 10000,
      currencyType: CurrencyType.coins,
      description: 'Casino VIP table high-density felt cloth.',
    ),
    ShopItem(
      id: 'tile_ocean_blue',
      name: 'Ocean Ripple',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/05_tile_skins_TileTab/Tile8.png',
      price: 15000,
      currencyType: CurrencyType.coins,
      description: 'Crystal Caribbean water ripple mosaic.',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 4. BUBBLE / AVATAR FRAMES
    // ════════════════════════════════════════════════════════════════════════
    ShopItem(
      id: 'bubble_classic',
      name: 'Classic Frame',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-4.png',
      price: 0,
      currencyType: CurrencyType.free,
      isOwned: true,
      isEquipped: true,
      description: 'Standard avatar frame border.',
    ),
    ShopItem(
      id: 'bubble_chick',
      name: 'Chick Bubble',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Rectangle.png',
      price: 5000,
      currencyType: CurrencyType.coins,
      description: 'Playful chirping chick bubble frame.',
    ),
    ShopItem(
      id: 'bubble_crown_glow',
      name: 'Crown Glow',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-5.png',
      price: 150,
      currencyType: CurrencyType.diamonds,
      description: 'Golden radiant royalty crown frame.',
    ),
    ShopItem(
      id: 'bubble_party',
      name: 'Party Bubble',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-6.png',
      price: 7500,
      currencyType: CurrencyType.coins,
      description: 'Celebration festival festive frame.',
    ),
    ShopItem(
      id: 'bubble_earth',
      name: 'Earth Frame',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Earth_power-3.png',
      price: 180,
      currencyType: CurrencyType.diamonds,
      description: 'Ancient earth stone runic power frame.',
    ),
    ShopItem(
      id: 'bubble_golden',
      name: 'Golden Frame',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Earth_power-4.png',
      price: 250,
      currencyType: CurrencyType.diamonds,
      description: 'Pure 24K shimmering gold filigree frame.',
    ),
    ShopItem(
      id: 'bubble_royal',
      name: 'Royal Frame',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Earth_power-5.png',
      price: 350,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      description: 'Emperor royal sovereign crest frame.',
    ),
    ShopItem(
      id: 'bubble_nature',
      name: 'Nature Frame',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Earth_power-6.png',
      price: 9000,
      currencyType: CurrencyType.coins,
      description: 'Lush blooming emerald vine wreath frame.',
    ),
    ShopItem(
      id: 'bubble_violet_star',
      name: 'Violet Star',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-7.png',
      price: 12000,
      currencyType: CurrencyType.coins,
      description: 'Cosmic celestial violet stellar frame.',
    ),
    ShopItem(
      id: 'bubble_silver_wave',
      name: 'Silver Wave',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-8.png',
      price: 14000,
      currencyType: CurrencyType.coins,
      description: 'Sleek chrome ocean tide avatar frame.',
    ),
    ShopItem(
      id: 'bubble_emerald_shine',
      name: 'Emerald Shine',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-9.png',
      price: 220,
      currencyType: CurrencyType.diamonds,
      description: 'Radiant glowing emerald crystal border.',
    ),
    ShopItem(
      id: 'bubble_sunset_ribbon',
      name: 'Sunset Ribbon',
      category: ShopCategory.bubble,
      imageAsset: 'assets/graphics/shop/02_token_speech_bubble_frames_BubbleTab/Classic-10.png',
      price: 16000,
      currencyType: CurrencyType.coins,
      description: 'Warm glowing sunset horizon gradient frame.',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 5. STICKERS (PACKS & SINGLE STICKERS)
    // ════════════════════════════════════════════════════════════════════════
    // Packs
    ShopItem(
      id: 'sticker_pack_fox',
      name: 'Fox Adventure Pack',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_fox_yay_flower.png',
      price: 99,
      currencyType: CurrencyType.diamonds,
      description: 'Expressive animated fox stickers for in-game banter.',
    ),
    ShopItem(
      id: 'sticker_pack_cute_pets',
      name: 'Cute Pets Pack',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_corgi_love.png',
      price: 149,
      currencyType: CurrencyType.diamonds,
      description: 'Adorably animated kittens, pups and chicks.',
    ),
    ShopItem(
      id: 'sticker_pack_party_frog',
      name: 'Party Frog Pack',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_frog_throw_confetti.png',
      price: 120,
      currencyType: CurrencyType.diamonds,
      description: 'Colorful festive confetti & celebration stickers.',
    ),
    ShopItem(
      id: 'sticker_pack_penguin',
      name: 'Penguin Melody Pack',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_penguin_music_moment.png',
      price: 180,
      currencyType: CurrencyType.diamonds,
      description: 'Charming penguin reactions and vibes.',
    ),

    // Singles
    ShopItem(
      id: 'sticker_single_cat_coffee',
      name: 'Coffee Cat',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_cat_coffee.png',
      price: 15,
      currencyType: CurrencyType.diamonds,
      description: 'Cozy coffee drinking cat.',
    ),
    ShopItem(
      id: 'sticker_single_cat_cool',
      name: 'Cool Sunglasses Cat',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_cat_cool_sunglasses.png',
      price: 20,
      currencyType: CurrencyType.diamonds,
      description: 'Supreme stylish sunglasses flex.',
    ),
    ShopItem(
      id: 'sticker_single_corgi',
      name: 'Corgi Love',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_corgi_love.png',
      price: 20,
      currencyType: CurrencyType.diamonds,
      description: 'Adorable loving puppy reaction.',
    ),
    ShopItem(
      id: 'sticker_single_fox',
      name: 'Fox Flower Cheer',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_fox_yay_flower.png',
      price: 25,
      currencyType: CurrencyType.diamonds,
      description: 'Celebratory happy flower dance.',
    ),
    ShopItem(
      id: 'sticker_single_frog_confetti',
      name: 'Frog Confetti',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_frog_throw_confetti.png',
      price: 25,
      currencyType: CurrencyType.diamonds,
      description: 'Confetti celebratory party blower.',
    ),
    ShopItem(
      id: 'sticker_single_penguin_music',
      name: 'Penguin Beats',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_penguin_music_moment.png',
      price: 30,
      currencyType: CurrencyType.diamonds,
      description: 'Listening to victory beats.',
    ),
    ShopItem(
      id: 'sticker_single_penguin_sorry',
      name: 'Sorry Penguin',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/10_sticker_skins/06_single_stickers/single_penguin_sorry.png',
      price: 30,
      currencyType: CurrencyType.diamonds,
      description: 'Humble apology after taking a pawn.',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 6. ROYAL EXCLUSIVES (LUXURY VEHICLES & AVATARS)
    // ════════════════════════════════════════════════════════════════════════
    ShopItem(
      id: 'royal_gold_lion',
      name: 'Golden Lion',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/RoyalLion.png',
      price: 1999,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 1,
      description: 'Mythical 24K solid gold lion companion avatar.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'royal_phoenix',
      name: 'Winged Lion',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/RoyalLionWithWings.png',
      price: 2499,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 2,
      description: 'Immortal celestial winged beast soaring across the boards.',
      glowColor: Color(0xFFFF6D00),
    ),
    ShopItem(
      id: 'royal_moon_chariot',
      name: 'Royal Carriage',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/RoyalCarrage.png',
      price: 2999,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 3,
      description: 'Celestial golden carriage pulled across the stars.',
      glowColor: Color(0xFF80D8FF),
    ),
    ShopItem(
      id: 'royal_spaceship',
      name: 'Royal Fighter Jet',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/RoyalFighterJet.png',
      price: 3499,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 4,
      description: 'Hyperspeed supersonic jet entry effect vehicle.',
      glowColor: Color(0xFF00E5FF),
    ),
    ShopItem(
      id: 'royal_yacht',
      name: 'Luxury Super Yacht',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/RoyalYacht.png',
      price: 3999,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'Multi-deck gold-trimmed mega yacht for VIP champions.',
      glowColor: Color(0xFF00B0FF),
    ),
    ShopItem(
      id: 'royal_golden_orv',
      name: 'Royal Jeep',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/RoyalJeep.png',
      price: 4499,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'All-terrain armored luxury golden tactical off-roader.',
      glowColor: Color(0xFFFFD600),
    ),
    ShopItem(
      id: 'royal_car',
      name: 'Royal Grand Tourer',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/RoyalCar.png',
      price: 4999,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 6,
      description: 'Sovereign golden supercar cruising the battlefield.',
      glowColor: Color(0xFFFFAB00),
    ),
    ShopItem(
      id: 'royal_white_tiger',
      name: 'Royal Tiger',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/RoyalTiger.png',
      price: 3199,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 4,
      description: 'Fierce mystical white tiger with glowing sapphire eyes.',
      glowColor: Color(0xFF448AFF),
    ),
    ShopItem(
      id: 'royal_golden_phantom',
      name: 'Golden Phantom',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/vehicle_golden_phantom.png',
      price: 3799,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'Spectral golden hypercar radiating royal prestige.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'royal_dragon_throne',
      name: 'Dragon Throne',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/09_royal_vehicles/vehicle_dragon_throne.png',
      price: 4500,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 6,
      description: 'Emperor dragon throne forged from golden scales.',
      glowColor: Color(0xFFFF9100),
    ),
  ];
}
