import 'package:flutter/material.dart';

enum ShopCategory {
  all('All', Icons.grid_view_rounded),
  dice('Dice', Icons.casino_rounded),
  token('Token', Icons.token_rounded),
  theme('Theme', Icons.wallpaper_rounded),
  tile('Tile', Icons.dashboard_rounded),
  stickers('Stickers', Icons.sticky_note_2_rounded),
  royal('Royal Exclusives', Icons.military_tech_rounded);

  final String label;
  final IconData icon;
  const ShopCategory(this.label, this.icon);
}

enum CurrencyType {
  coins('Coins', 'assets/graphics/icon_coins.png'),
  diamonds('Diamonds', 'assets/graphics/icon_diamond.png'),
  royalVip('Royal VIP', 'assets/graphics/shop/badges_selection_indicators/Crown.png'),
  free('Free', '');

  final String label;
  final String iconAsset;
  const CurrencyType(this.label, this.iconAsset);
}

enum ThemeType {
  basic,
  royal,
}

enum StickerType {
  pack,
  single,
}

class ShopItem {
  final String id;
  final String name;
  final ShopCategory category;
  final String imageAsset;
  final int price;
  final CurrencyType currencyType;
  final bool isOwned;
  final bool isEquipped;
  final bool isRoyalOnly;
  final String description;
  final ThemeType? themeType;
  final StickerType? stickerType;
  final List<String>? previewAssets;
  final int? royalVipLevel;
  final Color? glowColor;

  const ShopItem({
    required this.id,
    required this.name,
    required this.category,
    required this.imageAsset,
    required this.price,
    this.currencyType = CurrencyType.coins,
    this.isOwned = false,
    this.isEquipped = false,
    this.isRoyalOnly = false,
    this.description = '',
    this.themeType,
    this.stickerType,
    this.previewAssets,
    this.royalVipLevel,
    this.glowColor,
  });

  ShopItem copyWith({
    String? id,
    String? name,
    ShopCategory? category,
    String? imageAsset,
    int? price,
    CurrencyType? currencyType,
    bool? isOwned,
    bool? isEquipped,
    bool? isRoyalOnly,
    String? description,
    ThemeType? themeType,
    StickerType? stickerType,
    List<String>? previewAssets,
    int? royalVipLevel,
    Color? glowColor,
  }) {
    return ShopItem(
      id: id ?? this.id,
      name: name ?? this.name,
      category: category ?? this.category,
      imageAsset: imageAsset ?? this.imageAsset,
      price: price ?? this.price,
      currencyType: currencyType ?? this.currencyType,
      isOwned: isOwned ?? this.isOwned,
      isEquipped: isEquipped ?? this.isEquipped,
      isRoyalOnly: isRoyalOnly ?? this.isRoyalOnly,
      description: description ?? this.description,
      themeType: themeType ?? this.themeType,
      stickerType: stickerType ?? this.stickerType,
      previewAssets: previewAssets ?? this.previewAssets,
      royalVipLevel: royalVipLevel ?? this.royalVipLevel,
      glowColor: glowColor ?? this.glowColor,
    );
  }
}

/// Catalog data source containing all shop items accurately mapped to assets
class ShopCatalog {
  static const List<ShopItem> allItems = [
    // ════════════════════════════════════════════════════════════════════════
    // 1. DICE SKINS
    // ════════════════════════════════════════════════════════════════════════
    ShopItem(
      id: 'dice_classic',
      name: 'Classic',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Classic.png',
      price: 0,
      currencyType: CurrencyType.free,
      isOwned: true,
      isEquipped: true,
      description: 'The standard timeless Ludo dice.',
      glowColor: Color(0xFF5641F8),
    ),
    ShopItem(
      id: 'dice_chick',
      name: 'Chick',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Chick.png',
      price: 5000,
      currencyType: CurrencyType.coins,
      description: 'Cute chirping chick skin for charming luck.',
      glowColor: Color(0xFFFFD369),
    ),
    ShopItem(
      id: 'dice_coffee',
      name: 'Coffee',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Cofee.png',
      price: 8000,
      currencyType: CurrencyType.coins,
      description: 'Warm, energized morning espresso roll.',
      glowColor: Color(0xFFC07A48),
    ),
    ShopItem(
      id: 'dice_crystal',
      name: 'Crystal',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Crystal.png',
      price: 150,
      currencyType: CurrencyType.diamonds,
      description: 'Pure radiant gemstone crystal of fortune.',
      glowColor: Color(0xFF00E5FF),
    ),
    ShopItem(
      id: 'dice_dessert',
      name: 'Dessert',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Dessert.png',
      price: 6500,
      currencyType: CurrencyType.coins,
      description: 'Sweet frosted confectionery celebration piece.',
      glowColor: Color(0xFFFF69B4),
    ),
    ShopItem(
      id: 'dice_earth_power',
      name: 'Earth Power',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Earth_power.png',
      price: 250,
      currencyType: CurrencyType.diamonds,
      description: 'Harness the primordial terra element on each turn.',
      glowColor: Color(0xFF4CAF50),
    ),
    ShopItem(
      id: 'dice_fantasy_book',
      name: 'Fantasy Book',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Fantasy_Book.png',
      price: 12000,
      currencyType: CurrencyType.coins,
      description: 'Ancient spellbook containing magical roll secrets.',
      glowColor: Color(0xFFAB47BC),
    ),
    ShopItem(
      id: 'dice_ice_cream',
      name: 'Ice Cream',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Icecream.png',
      price: 7500,
      currencyType: CurrencyType.coins,
      description: 'Chilled gelato scoop for ultra smooth rolling.',
      glowColor: Color(0xFFFF80AB),
    ),
    ShopItem(
      id: 'dice_leisure_kitty',
      name: 'Leisure Kitty',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Leisure_kitty.png',
      price: 180,
      currencyType: CurrencyType.diamonds,
      description: 'Playful feline buddy bringing purr-fect high numbers.',
      glowColor: Color(0xFFFFB74D),
    ),
    ShopItem(
      id: 'dice_rosy_life',
      name: 'Rosy Life',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Rosy_Life.png',
      price: 10000,
      currencyType: CurrencyType.coins,
      description: 'Blooming crimson petals overflowing with luck.',
      glowColor: Color(0xFFE91E63),
    ),
    ShopItem(
      id: 'dice_warm_campfire',
      name: 'Warm Campfire',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Warm_Campfire.png',
      price: 14000,
      currencyType: CurrencyType.coins,
      description: 'Cozy glowing embers that blaze through opponent tokens.',
      glowColor: Color(0xFFFF5722),
    ),
    ShopItem(
      id: 'dice_warrior_helmet',
      name: 'Warrior Helmet',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Metal.png',
      price: 320,
      currencyType: CurrencyType.diamonds,
      description: 'Armored battle helmet of the invincible champion.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'dice_wooden_case',
      name: 'Wooden Case',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Wooden_Case.png',
      price: 4500,
      currencyType: CurrencyType.coins,
      description: 'Handcrafted polished mahogany treasure chest dice.',
      glowColor: Color(0xFF8D6E63),
    ),
    ShopItem(
      id: 'dice_blessing_basket',
      name: 'Blessing Basket',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Blessing_Basket.png',
      price: 9500,
      currencyType: CurrencyType.coins,
      description: 'Festival basket filled with prosperity and sixes.',
      glowColor: Color(0xFF26A69A),
    ),
    ShopItem(
      id: 'dice_desert_hammer',
      name: 'Desert Hammer',
      category: ShopCategory.dice,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Desert_Hammer-2.png',
      price: 210,
      currencyType: CurrencyType.diamonds,
      description: 'Forged under dunes to strike down rival pieces.',
      glowColor: Color(0xFFFFA726),
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 2. TOKENS (4-PIECE PAWN SETS)
    // ════════════════════════════════════════════════════════════════════════
    ShopItem(
      id: 'token_classic',
      name: 'Classic Pieces',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Classic.png',
      price: 0,
      currencyType: CurrencyType.free,
      isOwned: true,
      isEquipped: true,
      description: 'The standard timeless Ludo piece set.',
      glowColor: Color(0xFF5641F8),
    ),
    ShopItem(
      id: 'token_chick',
      name: 'Chick Set',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Chick-4.png',
      price: 5000,
      currencyType: CurrencyType.coins,
      description: 'Cute chirping chick pawn pieces.',
      glowColor: Color(0xFFFFD369),
    ),
    ShopItem(
      id: 'token_coffee',
      name: 'Coffee Set',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Cofee-3.png',
      price: 8000,
      currencyType: CurrencyType.coins,
      description: 'Warm energizing coffee cup tokens.',
      glowColor: Color(0xFFC07A48),
    ),
    ShopItem(
      id: 'token_blessing_basket',
      name: 'Blessing Basket',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Blessing_Basket-3.png',
      price: 9500,
      currencyType: CurrencyType.coins,
      description: 'Festival blessing basket pawns.',
      glowColor: Color(0xFF26A69A),
    ),
    ShopItem(
      id: 'token_desert_hammer',
      name: 'Desert Hammer',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Desert_Hammer-2.png',
      price: 210,
      currencyType: CurrencyType.diamonds,
      description: 'Dune forged battle hammer tokens.',
      glowColor: Color(0xFFFFA726),
    ),
    ShopItem(
      id: 'token_earth_power',
      name: 'Earth Power',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Earth_power-7.png',
      price: 250,
      currencyType: CurrencyType.diamonds,
      description: 'Primordial terra crystals of power.',
      glowColor: Color(0xFF4CAF50),
    ),
    ShopItem(
      id: 'token_fantasy_book',
      name: 'Fantasy Book',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Fantasy_Book-3.png',
      price: 12000,
      currencyType: CurrencyType.coins,
      description: 'Ancient spellbook pieces.',
      glowColor: Color(0xFFAB47BC),
    ),
    ShopItem(
      id: 'token_ice_cream',
      name: 'Ice Cream',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Icecream-3.png',
      price: 7500,
      currencyType: CurrencyType.coins,
      description: 'Sweet creamy gelato tokens.',
      glowColor: Color(0xFFFF80AB),
    ),
    ShopItem(
      id: 'token_leisure_kitty',
      name: 'Leisure Kitty',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Leisure_kitty-3.png',
      price: 180,
      currencyType: CurrencyType.diamonds,
      description: 'Playful companion feline pawns.',
      glowColor: Color(0xFFFFB74D),
    ),
    ShopItem(
      id: 'token_rosy_life',
      name: 'Rosy Life',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Rosy_Life-3.png',
      price: 10000,
      currencyType: CurrencyType.coins,
      description: 'Crimson rose petal tokens.',
      glowColor: Color(0xFFE91E63),
    ),
    ShopItem(
      id: 'token_warm_campfire',
      name: 'Warm Campfire',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Warm_Campfire-3.png',
      price: 14000,
      currencyType: CurrencyType.coins,
      description: 'Blazing campfire tokens.',
      glowColor: Color(0xFFFF5722),
    ),
    ShopItem(
      id: 'token_wooden_case',
      name: 'Wooden Case',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/03_piece_color_sets_TokenTab/Wooden_Case-2.png',
      price: 4500,
      currencyType: CurrencyType.coins,
      description: 'Polished wooden treasure chest tokens.',
      glowColor: Color(0xFF8D6E63),
    ),
    ShopItem(
      id: 'token_crystal',
      name: 'Crystal Pieces',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Crystal.png',
      price: 150,
      currencyType: CurrencyType.diamonds,
      description: 'Pure radiant gemstone crystal piece set.',
      glowColor: Color(0xFF00E5FF),
    ),
    ShopItem(
      id: 'token_dessert',
      name: 'Dessert Pieces',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Dessert.png',
      price: 6500,
      currencyType: CurrencyType.coins,
      description: 'Sweet frosted confectionery celebration tokens.',
      glowColor: Color(0xFFFF69B4),
    ),
    ShopItem(
      id: 'token_warrior_helmet',
      name: 'Warrior Helmet Pieces',
      category: ShopCategory.token,
      imageAsset: 'assets/graphics/shop/01_dice_skins_DiceTab/Metal.png',
      price: 320,
      currencyType: CurrencyType.diamonds,
      description: 'Armored metal battle helmet pawn set.',
      glowColor: Color(0xFFFFD700),
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 2. THEMES (BASIC & ROYAL WALLPAPERS)
    // ════════════════════════════════════════════════════════════════════════
    // Basic Themes
    ShopItem(
      id: 'theme_green_silk',
      name: 'Green Silk',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Green Silk.png',
      price: 0,
      currencyType: CurrencyType.free,
      isOwned: true,
      isEquipped: true,
      description: 'Emerald satin silk table board atmosphere.',
    ),
    ShopItem(
      id: 'theme_golden_mountain',
      name: 'Golden Mountain',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153344.png',
      price: 20000,
      currencyType: CurrencyType.coins,
      description: 'Magnificent golden peaks glowing under sunlight.',
    ),
    ShopItem(
      id: 'theme_sky_wheel',
      name: 'Sky Wheel',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153345.png',
      price: 25000,
      currencyType: CurrencyType.coins,
      description: 'Luminous amusement park ferris wheel night vista.',
    ),
    ShopItem(
      id: 'theme_fantastic_lion',
      name: 'Fantastic Lion',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153346.png',
      price: 30000,
      currencyType: CurrencyType.coins,
      description: 'Majestic celestial lion overlooking the battlefield.',
    ),
    ShopItem(
      id: 'theme_bonfire',
      name: 'Bonfire Night',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153347.png',
      price: 18000,
      currencyType: CurrencyType.coins,
      description: 'Crackling starry night gathering by the warm fire.',
    ),
    ShopItem(
      id: 'theme_waterfall',
      name: 'Waterfall Valley',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153348.png',
      price: 22000,
      currencyType: CurrencyType.coins,
      description: 'Cascading pristine alpine waterfalls in lush paradise.',
    ),
    ShopItem(
      id: 'theme_cloudy_sky',
      name: 'Cloudy Sky',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Cloudy Sky.png',
      price: 15000,
      currencyType: CurrencyType.coins,
      description: 'Soothing pastel twilight clouds drift serenely.',
    ),
    ShopItem(
      id: 'theme_blue_moon',
      name: 'Blue Moon',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Blue Moon.png',
      price: 28000,
      currencyType: CurrencyType.coins,
      description: 'Rare full blue moon radiating tranquil midnight aura.',
    ),
    ShopItem(
      id: 'theme_eternal_lighthouse',
      name: 'Eternal Lighthouse',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Eternal Light House.png',
      price: 32000,
      currencyType: CurrencyType.coins,
      description: 'Guiding marine beacon cutting through oceanic fog.',
    ),
    ShopItem(
      id: 'theme_indigo_wallpaper',
      name: 'Indigo Twilight',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Indigo wallpaper.png',
      price: 16000,
      currencyType: CurrencyType.coins,
      description: 'Deep violet gradient backdrop with subtle star dust.',
    ),
    ShopItem(
      id: 'theme_urban_twilight',
      name: 'Urban Twilight',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Urban Twilight.png',
      price: 24000,
      currencyType: CurrencyType.coins,
      description: 'Modern metropolis skyline lit by glowing neon skyscrapers.',
    ),
    ShopItem(
      id: 'theme_spring_letter',
      name: 'Letter from Spring',
      category: ShopCategory.theme,
      themeType: ThemeType.basic,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Letter from spring.png',
      price: 19000,
      currencyType: CurrencyType.coins,
      description: 'Delicate sakura cherry blossom breeze across paper.',
    ),

    // Royal Themes
    ShopItem(
      id: 'theme_royal_twilight_knight',
      name: 'Twilight Knight',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153349.png',
      price: 500,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 1,
      description: 'Royal armory hall guarded by eternal silver paladins.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'theme_royal_red_car',
      name: 'Red Car Beneath Snow',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153350.png',
      price: 650,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 2,
      description: 'Luxury grand tourer cruising alpine winter wonderlands.',
      glowColor: Color(0xFFFF5252),
    ),
    ShopItem(
      id: 'theme_royal_couple_dusk',
      name: 'Couple at Dusk',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153351.png',
      price: 800,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 2,
      description: 'Romantic sunset promenade with golden hour reflections.',
      glowColor: Color(0xFFFF7043),
    ),
    ShopItem(
      id: 'theme_royal_dream_garden',
      name: 'Dream Garden',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153352.png',
      price: 950,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 3,
      description: 'Enchanted palace conservatory filled with bioluminescent flora.',
      glowColor: Color(0xFF7C4DFF),
    ),
    ShopItem(
      id: 'theme_royal_mountain',
      name: 'Mountain Summit',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Group 1261153353.png',
      price: 1100,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 3,
      description: 'Imperial throne chamber overlooking endless snow peaks.',
      glowColor: Color(0xFF00E5FF),
    ),
    ShopItem(
      id: 'theme_royal_jellyfish',
      name: 'Fantastic Jellyfish',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Fantastic Jellyfish.png',
      price: 1200,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 4,
      description: 'Deep oceanic abyss shimmering with golden neon jellyfish.',
      glowColor: Color(0xFF651FFF),
    ),
    ShopItem(
      id: 'theme_royal_black_gold',
      name: 'Black and Gold',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Black and Gold.png',
      price: 1500,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'Ultra-exclusive 24K gold foil layered on obsidian marble.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'theme_royal_sea_moon',
      name: 'Moon in the Sea',
      category: ShopCategory.theme,
      themeType: ThemeType.royal,
      imageAsset: 'assets/graphics/shop/theme_wallpaper_cards/Moon in the sea.png',
      price: 1800,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'Imperial lunar eclipse casting silver brilliance upon tides.',
      glowColor: Color(0xFF8C9EFF),
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 3. TILES (BOARD TEXTURE SWATCHES)
    // ════════════════════════════════════════════════════════════════════════
    ShopItem(
      id: 'tile_wood',
      name: 'Classic Wood',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 610.png',
      price: 0,
      currencyType: CurrencyType.free,
      isOwned: true,
      isEquipped: true,
      description: 'Polished walnut wood parquet texture.',
    ),
    ShopItem(
      id: 'tile_garden',
      name: 'Garden Grass',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 612.png',
      price: 8000,
      currencyType: CurrencyType.coins,
      description: 'Fresh manicured spring lawn fairway pattern.',
    ),
    ShopItem(
      id: 'tile_egyptian',
      name: 'Egyptian Civilization',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 613.png',
      price: 180,
      currencyType: CurrencyType.diamonds,
      description: 'Hieroglyphic carved golden sandstone tile.',
    ),
    ShopItem(
      id: 'tile_football',
      name: 'Football Pitch',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 614.png',
      price: 12000,
      currencyType: CurrencyType.coins,
      description: 'Stadium turf with precision yard line markings.',
    ),
    ShopItem(
      id: 'tile_basketball',
      name: 'Basketball Court',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 615.png',
      price: 14000,
      currencyType: CurrencyType.coins,
      description: 'Indoor hardwood polished court with paint lines.',
    ),
    ShopItem(
      id: 'tile_purple_silk',
      name: 'Purple Silk',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 616.png',
      price: 220,
      currencyType: CurrencyType.diamonds,
      description: 'Imperial velvet tapestry with delicate stitching.',
    ),
    ShopItem(
      id: 'tile_dark_green',
      name: 'Dark Green Felt',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 617.png',
      price: 10000,
      currencyType: CurrencyType.coins,
      description: 'Casino VIP table high-density felt cloth.',
    ),
    ShopItem(
      id: 'tile_ocean_blue',
      name: 'Ocean Blue',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 618.png',
      price: 15000,
      currencyType: CurrencyType.coins,
      description: 'Crystal Caribbean water ripple mosaic.',
    ),
    ShopItem(
      id: 'tile_golden_sand',
      name: 'Golden Sand',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 619.png',
      price: 16000,
      currencyType: CurrencyType.coins,
      description: 'Sun-drenched tropical beach shore texture.',
    ),
    ShopItem(
      id: 'tile_neon_cyber',
      name: 'Neon Cyber',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 620.png',
      price: 300,
      currencyType: CurrencyType.diamonds,
      description: 'Futuristic illuminated circuit board matrix.',
    ),
    ShopItem(
      id: 'tile_royal_marble',
      name: 'Royal Marble',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/image 621.png',
      price: 450,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      description: 'Carrara white marble infused with 24K gold veining.',
    ),
    ShopItem(
      id: 'tile_swimming_pool',
      name: 'Swimming Pool',
      category: ShopCategory.tile,
      imageAsset: 'assets/graphics/shop/tile_board_skins/Swimming Pool.png',
      price: 20000,
      currencyType: CurrencyType.coins,
      description: 'Refreshing pool ceramic tile grid with sun glints.',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 4. STICKERS (PACKS & SINGLE STICKERS)
    // ════════════════════════════════════════════════════════════════════════
    // Packs
    ShopItem(
      id: 'sticker_pack_emotion',
      name: 'Emotion Mega Pack',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 240.png',
      price: 99,
      currencyType: CurrencyType.diamonds,
      description: '12 expressive animated stickers for in-game banter.',
      previewAssets: [
        'assets/graphics/shop/misc_uncategorized/image 280.png',
        'assets/graphics/shop/misc_uncategorized/image 281.png',
        'assets/graphics/shop/misc_uncategorized/image 282.png',
        'assets/graphics/shop/misc_uncategorized/image 283.png',
      ],
    ),
    ShopItem(
      id: 'sticker_pack_victory',
      name: 'Victory Express Pack',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 241.png',
      price: 149,
      currencyType: CurrencyType.diamonds,
      description: '8 high-energy winner taunts & celebration fireworks.',
      previewAssets: [
        'assets/graphics/shop/misc_uncategorized/image 284.png',
        'assets/graphics/shop/misc_uncategorized/image 285.png',
        'assets/graphics/shop/misc_uncategorized/image 286.png',
      ],
    ),
    ShopItem(
      id: 'sticker_pack_cute_pets',
      name: 'Cute Pets Pack',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 242.png',
      price: 199,
      currencyType: CurrencyType.diamonds,
      description: '10 adorably animated kittens, pups and chicks.',
      previewAssets: [
        'assets/graphics/shop/misc_uncategorized/image 288.png',
        'assets/graphics/shop/misc_uncategorized/image 289.png',
        'assets/graphics/shop/misc_uncategorized/image 290.png',
      ],
    ),
    ShopItem(
      id: 'sticker_pack_royal_vip',
      name: 'Royal VIP Gestures',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 243.png',
      price: 299,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      description: '15 ultra luxury golden reactions & crown flexes.',
      previewAssets: [
        'assets/graphics/shop/misc_uncategorized/image 291.png',
        'assets/graphics/shop/misc_uncategorized/image 292.png',
        'assets/graphics/shop/misc_uncategorized/image 293.png',
      ],
    ),
    ShopItem(
      id: 'sticker_pack_festival',
      name: 'Festival Blast Pack',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 244.png',
      price: 120,
      currencyType: CurrencyType.diamonds,
      description: '6 colorful festival confetti & dance cheer stickers.',
      previewAssets: [
        'assets/graphics/shop/misc_uncategorized/image 294.png',
        'assets/graphics/shop/misc_uncategorized/image 581.png',
        'assets/graphics/shop/misc_uncategorized/image 582.png',
      ],
    ),
    ShopItem(
      id: 'sticker_pack_diamond',
      name: 'Diamond Sparkle Pack',
      category: ShopCategory.stickers,
      stickerType: StickerType.pack,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 245.png',
      price: 249,
      currencyType: CurrencyType.diamonds,
      description: '12 sparkling animated diamond icons & glow seals.',
      previewAssets: [
        'assets/graphics/shop/misc_uncategorized/image 583.png',
        'assets/graphics/shop/misc_uncategorized/image 584.png',
        'assets/graphics/shop/misc_uncategorized/image 585.png',
      ],
    ),

    // Singles
    ShopItem(
      id: 'sticker_single_thumbs_up',
      name: 'Thumbs Up Cool',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 280.png',
      price: 15,
      currencyType: CurrencyType.diamonds,
      description: 'Classic thumbs up sticker.',
    ),
    ShopItem(
      id: 'sticker_single_laugh',
      name: 'Laughing Loud',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 281.png',
      price: 15,
      currencyType: CurrencyType.diamonds,
      description: 'Hilarious rolling laugh sticker.',
    ),
    ShopItem(
      id: 'sticker_single_cry',
      name: 'Crying Tear',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 282.png',
      price: 15,
      currencyType: CurrencyType.diamonds,
      description: 'Dramatic bad roll cry sticker.',
    ),
    ShopItem(
      id: 'sticker_single_angry',
      name: 'Angry Fire',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 283.png',
      price: 20,
      currencyType: CurrencyType.diamonds,
      description: 'Burning revenge rage sticker.',
    ),
    ShopItem(
      id: 'sticker_single_party',
      name: 'Party Horn',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 284.png',
      price: 20,
      currencyType: CurrencyType.diamonds,
      description: 'Confetti celebratory party blower.',
    ),
    ShopItem(
      id: 'sticker_single_cat',
      name: 'Surprised Kitty',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 285.png',
      price: 25,
      currencyType: CurrencyType.diamonds,
      description: 'Wide-eyed amazed kitten face.',
    ),
    ShopItem(
      id: 'sticker_single_crown',
      name: 'Crown Flex',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 286.png',
      price: 35,
      currencyType: CurrencyType.diamonds,
      description: 'Gold crown tip to the true victor.',
    ),
    ShopItem(
      id: 'sticker_single_wink',
      name: 'Diamond Wink',
      category: ShopCategory.stickers,
      stickerType: StickerType.single,
      imageAsset: 'assets/graphics/shop/misc_uncategorized/image 288.png',
      price: 30,
      currencyType: CurrencyType.diamonds,
      description: 'Charming sneaky wink.',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // 5. ROYAL EXCLUSIVES (LUXURY VEHICLES & AVATARS)
    // ════════════════════════════════════════════════════════════════════════
    ShopItem(
      id: 'royal_gold_lion',
      name: 'Golden Lion',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 529.png',
      price: 1999,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 1,
      description: 'Mythical 24K solid gold lion companion avatar.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'royal_phoenix',
      name: 'Solar Phoenix',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 530.png',
      price: 2499,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 2,
      description: 'Immortal firebird blazing across the boards with wings of fire.',
      glowColor: Color(0xFFFF6D00),
    ),
    ShopItem(
      id: 'royal_moon_chariot',
      name: 'Moon Chariot',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 531.png',
      price: 2999,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 3,
      description: 'Celestial carriage pulled by moonlight across the stars.',
      glowColor: Color(0xFF80D8FF),
    ),
    ShopItem(
      id: 'royal_spaceship',
      name: 'Cyber Spaceship',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 532.png',
      price: 3499,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 4,
      description: 'Hyperspeed interstellar cruiser entry effect vehicle.',
      glowColor: Color(0xFF00E5FF),
    ),
    ShopItem(
      id: 'royal_yacht',
      name: 'Luxury Super Yacht',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 533.png',
      price: 3999,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'Multi-deck gold-trimmed mega yacht for VIP champions.',
      glowColor: Color(0xFF00B0FF),
    ),
    ShopItem(
      id: 'royal_golden_orv',
      name: 'Golden ORV',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 534.png',
      price: 4499,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'All-terrain armored luxury golden tactical off-roader.',
      glowColor: Color(0xFFFFD600),
    ),
    ShopItem(
      id: 'royal_imperial_dragon',
      name: 'Imperial Dragon',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 535.png',
      price: 4999,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 6,
      description: 'Ancient serpentine golden dragon unleashing lightning roars.',
      glowColor: Color(0xFFFFAB00),
    ),
    ShopItem(
      id: 'royal_gorgeous_carriage',
      name: 'Gorgeous Carriage',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 536.png',
      price: 3299,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 4,
      description: 'Enchanted glass and pearl royal imperial stagecoach.',
      glowColor: Color(0xFFE040FB),
    ),
    ShopItem(
      id: 'royal_majesty_throne',
      name: 'Majesty Throne',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 537.png',
      price: 3799,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 5,
      description: 'Jeweled throne of the supreme grandmaster of Ludo.',
      glowColor: Color(0xFFFFD700),
    ),
    ShopItem(
      id: 'royal_frost_fire_blade',
      name: 'Frost Fire Blade',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 538.png',
      price: 2799,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 3,
      description: 'Dual-element legendary broadsword charged with ice and flame.',
      glowColor: Color(0xFF00E676),
    ),
    ShopItem(
      id: 'royal_white_tiger',
      name: 'White Tiger',
      category: ShopCategory.royal,
      imageAsset: 'assets/graphics/shop/royal_avatars_vehicles/image 539.png',
      price: 3199,
      currencyType: CurrencyType.diamonds,
      isRoyalOnly: true,
      royalVipLevel: 4,
      description: 'Fierce mystical white tiger with glowing sapphire eyes.',
      glowColor: Color(0xFF448AFF),
    ),
  ];
}
